### ISSUE TITLE
Percentage of the result

### ISSUE THREAD

**Issue by stezarpriansya** [andreypurwanto/andreyfastapi#1]
Hi Andrey, this is very interesting, great repository with clear Readme. Good job!

I found an issue on the value of the percentage on your '/selisih' endpoint result. It seems not represent of percentage, because percentage have 100% max (as you can see below). Could you mind to explain more about this?
![image](https://user-images.githubusercontent.com/7480754/116673525-b4b3bc80-a9cd-11eb-8c4a-b50d1455a49c.png)

Thanks.

**Comment by andreypurwanto** [comment]
Thank you kak @stezarpriansya , 

so, all of the percentage formula will use this function

def percentage_calc(initial,end):

    """return nan if divide by zero, else return ((end-initial)/initial)*100"""
    if initial == 0:
        return np.nan
    else:
        return ((end-initial)/initial)*100`


which will represent the difference percentage between 2 dates,
for example if initial positive case is 10, and on the next day the case increase to 12, means that the case is increasing (10-2)/10 or 20%.
If the intial case is 10 and then the end case is 40 it means that the case increasing 30/10 or 300%.

another example in the program, i select 2 case which:
![image](https://user-images.githubusercontent.com/64034905/116684375-162e5800-a9db-11eb-9f20-01f2d9ecf5f4.png)

as we can see postitive case is increasing from 8 to 24, or 16/8 = 200%. 
![image](https://user-images.githubusercontent.com/64034905/116684529-3f4ee880-a9db-11eb-92df-a0dd1f2b5795.png)

the positive rate is 200%, while "meninggal" is 0% because there is no difference between initial and end and the initial value is not 0. But the "sembuh" is undefined because initial value is 0, thus it will be divide be zero to count the difference rate.

I am sorry mas stezar for lack of documentation in selisih case.

Thank you.

**Comment by stezarpriansya** [comment]
> Thank you kak @stezarpriansya ,
> 
> so, all of the percentage formula will use this function
> 
> def percentage_calc(initial,end):
> 
> ```
> """return nan if divide by zero, else return ((end-initial)/initial)*100"""
> if initial == 0:
>     return np.nan
> else:
>     return ((end-initial)/initial)*100`
> ```
> 
> which will represent the difference percentage between 2 dates,
> for example if initial positive case is 10, and on the next day the case increase to 12, means that the case is increasing (10-2)/10 or 20%.
> If the intial case is 10 and then the end case is 40 it means that the case increasing 30/10 or 300%.
> 
> another example in the program, i select 2 case which:
> ![image](https://user-images.githubusercontent.com/64034905/116684375-162e5800-a9db-11eb-9f20-01f2d9ecf5f4.png)
> 
> as we can see postitive case is increasing from 8 to 24, or 16/8 = 200%.
> ![image](https://user-images.githubusercontent.com/64034905/116684529-3f4ee880-a9db-11eb-92df-a0dd1f2b5795.png)
> 
> the positive rate is 200%, while "meninggal" is 0% because there is no difference between initial and end and the initial value is not 0. But the "sembuh" is undefined because initial value is 0, thus it will be divide be zero to count the difference rate.
> 
> I am sorry mas stezar for lack of documentation in selisih case.
> 
> Thank you.

Thanks for the explanation yaa. Its very good!

Keep learning and practicing ya!
